server:
  port: 8080
  servlet:
    context-path: /eficienciaenergetica
spring:
  application:
    name: eficienciaenergetica
  profiles:
    active:
    - dev
  jpa:
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/dashboard_claro_tv
    username: postgres
    password: Sicoob!123
  mail:
     host: smtp.gmail.com
     port: 587
     username: henriquerdq@tcia.com.br
     password: aglf sbvo wjje lito
     properties:
       mail:
         smtp:
            auth: true
            starttls: 
               enable: true