app:
  url-site: "https://ct.tcia.com.br"
  empresa: "TCIA"
  acessar-sistema: "Clique aqui para acessar o sistema"
  empresa-principal: "Minha Empresa Principal"
  cadastro-msg: "Mensagem de Confirmação de Cadastro"
  ativacao-msg: "Sua conta foi ativada com sucesso"
  recuperar-senha: "Recuperação de Senha"
  entre-com-codigo-acima: "Insira o código acima no formulário"
  acesse-msg: "Clique no link abaixo para acessar o sistema"
  solicitacao-emitida: "Solicitação de Senha Realizada"
  desativacao-msg: "Sua conta foi desativada"
server:
  port: 8080
  servlet:
    context-path: /eficienciaenergetica
spring:
  application:
    name: eficienciaenergetica
  profiles:
    active:
    - dev
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/eficienciaenergetica
    username: postgres
    password: Sicoob!123
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  mail:
     host: smtp.gmail.com
     port: 587
     username: henriquerdq@tcia.com.br
     password: aglf sbvo wjje lito
     properties:
       mail:
         smtp:
            auth: true
            starttls: 
               enable: true